### PR TITLE
Update project tt_um_coloquinte_moosic (Coloquinte/locked-tapeout)

### PR DESCRIPTION
**Pull request by TinyTapeoutBot**
Update project tt_um_coloquinte_moosic to commit Coloquinte/locked-tapeout@d8310f01adc9fe4d7965abc41ef975a32394a991

Project title: Moosic logic-locked design
Tiles: 1x1
Workflow: https://github.com/Coloquinte/locked-tapeout/actions/runs/7697819275

### CODE REVIEW

**Comment by urish** [comment]
Hi @Coloquinte, can you please add the pinout to your [info.yaml file](https://github.com/Coloquinte/locked-tapeout/blob/main/info.yaml#L22-L51) and resubmit?

**Comment by Coloquinte** [comment]
Thank you!
I'm not familiar with the conventions. Would something like this do?

https://github.com/Coloquinte/locked-tapeout/commit/0936052d2e32f802bd040e6ce9384ab1b025b0ed

**Comment by urish** [comment]
I think so. You can see a preview of what this will look like in the datasheet here:

https://github.com/Coloquinte/locked-tapeout/actions/runs/7711914495

Scroll down and download the PDF artifact. Then imagine you are a user looking at the datasheet, and ask yourself: do I have enough information to figure out how to test the design?

**Comment by Coloquinte** [comment]
It's a pleasure to use :)

**Pull request closed without merging**
